#!/bin/sh
HURF=${PWD}
cd ~
if [[ -e ${PWD}/.vim ]]
then echo "${PWD}/.vim already exists."
else 
  ln -s ${HURF}/vim ${PWD}/.vim
  echo "${PWD}/.vim linked to ${HURF}/vim."
fi
if [[ -e ${PWD}/.vimrc ]]
then echo "${PWD}/.vimrc already exists."
else 
  ln -s ${HURF}/vimrc ${PWD}/.vimrc
  echo "${PWD}/.vimrc linked to ${HURF}/vimrc."
fi
if [[ -e ${PWD}/.irssi ]]
then echo "${PWD}/.irssi already exists."
else 
  ln -s ${HURF}/irssi ${PWD}/.irssi
  echo "${PWD}/.irssi linked to ${HURF}/irssi."
fi
